---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.154.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: aws/aws-cli@2.15.31
- name: hashicorp/terraform@v1.7.5
