---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.205.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: aws/aws-cli@2.17.14
- name: hashicorp/terraform@v1.9.2
- name: kayac/ecspresso@v2.3.5
