name: Lint Renovate
on:
  push:
    paths:
      - renovate.json5

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cybozu/renovate-dry-run-action@v1
        with:
          config-file: renovate.json5
