name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * 6,0" # 週末に実行

permissions:
  contents: read
  id-token: write # AWS OIDC

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}

      - uses: aws-actions/configure-aws-credentials@v4
        id: aws-credentials
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          output-credentials: true

      - uses: renovatebot/github-action@v42.0.5
        with:
          token: ${{ steps.app-token.outputs.token }}
          configurationFile: renovate.json5
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|AWS_\\w+)$"
        env:
          LOG_LEVEL: "debug"
          RENOVATE_REPOSITORIES: "['i544c-me/buicha-social']"
          AWS_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: ${{ steps.aws-credentials.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.aws-credentials.outputs.aws-secret-access-key }}
